# Generated by Django 3.1.4 on 2021-05-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_utilisateur',
            old_name='adress',
            new_name='avenu',
        ),
        migrations.AddField(
            model_name='model_utilisateur',
            name='commune',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='model_utilisateur',
            name='quartier',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
