# Generated by Django 3.1.4 on 2021-05-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_auto_20210511_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('Superficie', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
