# Generated by Django 3.1.4 on 2021-05-21 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_model_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_commune',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
