# Generated by Django 3.1.4 on 2021-05-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_model_commune_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_commune',
            name='localsation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
