# Generated by Django 3.1.4 on 2021-06-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0005_model_commune_localsation'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_utilisateur',
            name='typeuser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
