# Generated by Django 3.1.4 on 2021-07-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0006_model_utilisateur_typeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
