# Generated by Django 3.1.4 on 2021-07-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0007_auto_20210724_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_utilisateur',
            old_name='avenu',
            new_name='adress',
        ),
        migrations.RemoveField(
            model_name='model_utilisateur',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='model_utilisateur',
            name='quartier',
        ),
    ]
