# Generated by Django 3.1.1 on 2021-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0008_auto_20210729_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_parametreSuplementaireProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametre', models.CharField(blank=True, max_length=150, null=True)),
                ('valeur', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
