# Generated by Django 3.1.1 on 2021-08-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0009_model_parametresuplementaireproduit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_parametresuplementaireproduit',
            name='parametre',
        ),
    ]
