# Generated by Django 3.1.1 on 2021-08-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0010_remove_model_parametresuplementaireproduit_parametre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_valeurParametreeSuplementaireProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='model_parametresuplementaireproduit',
            old_name='valeur',
            new_name='parametre',
        ),
    ]
