# Generated by Django 3.1.1 on 2021-10-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0011_auto_20210822_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_parametresuplementaireproduit',
            name='parametre',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='model_valeurparametreesuplementaireproduit',
            name='valeur',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
