# Generated by Django 3.1.1 on 2023-01-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0013_auto_20230124_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Usser_Allow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSecret', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_allow', to='datacenter.model_utilisateur')),
            ],
        ),
    ]
