# Generated by Django 3.1.1 on 2023-01-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0014_model_usser_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_utilisateur',
            name='codex',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
