# Generated by Django 3.1.1 on 2023-01-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0015_model_utilisateur_codex'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_utilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='model_utilisateur',
            name='postnom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='model_utilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
