# Generated by Django 3.1.1 on 2023-02-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0016_auto_20230131_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_utilisateur',
            name='apropos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
