# Generated by Django 3.1.1 on 2023-02-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0017_model_utilisateur_apropos'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_utilisateur',
            name='code_ent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
