# Generated by Django 3.1.1 on 2023-02-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0018_model_utilisateur_code_ent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Moi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('e', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
