# Generated by Django 3.1.4 on 2021-03-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Utilisateur_esclave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(blank=True, max_length=2, null=True)),
                ('pays', models.CharField(blank=True, max_length=50, null=True)),
                ('adress', models.CharField(blank=True, max_length=150, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naissance', models.DateField()),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_utilisateur_esclave_user', to='security.model_utilisateur')),
            ],
        ),
    ]
