# Generated by Django 3.1.4 on 2021-04-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_model_utilisateur_esclave_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_utilisateur_esclave',
            name='user',
        ),
        migrations.RemoveField(
            model_name='model_utilisateur_esclave',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Model_Utilisateur',
        ),
        migrations.DeleteModel(
            name='Model_Utilisateur_esclave',
        ),
    ]
