# Generated by Django 3.1.1 on 2023-01-23 09:00

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.CharField(blank=True, max_length=50, null=True)),
                ('my_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/file'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Model_PersonneMorale',
            fields=[
                ('model_client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionCouriers.model_client')),
                ('intitule', models.CharField(blank=True, max_length=50, null=True)),
                ('Forme_juridique', models.CharField(blank=True, max_length=50, null=True)),
                ('rccm', models.CharField(blank=True, max_length=50, null=True)),
                ('siren', models.CharField(blank=True, max_length=150, null=True)),
                ('Date_création_entreprise', models.DateField()),
                ('Effectifs', models.CharField(blank=True, max_length=150, null=True)),
            ],
            bases=('GestionCouriers.model_client',),
        ),
        migrations.CreateModel(
            name='Model_PersonnePhysique',
            fields=[
                ('model_client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionCouriers.model_client')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('postnom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('sexe', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('GestionCouriers.model_client',),
        ),
    ]
