# Generated by Django 3.1.1 on 2023-01-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_client',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
