# Generated by Django 3.1.1 on 2023-01-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0012_auto_20211003_1520'),
        ('GestionCouriers', '0002_model_client_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_personnemorale',
            name='Date_création_entreprise',
        ),
        migrations.AddField(
            model_name='model_client',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.model_utilisateur'),
        ),
        migrations.AddField(
            model_name='model_personnemorale',
            name='Date_creation_entreprise',
            field=models.DateField(blank=True, null=True),
        ),
    ]
