# Generated by Django 3.1.1 on 2023-01-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0003_auto_20230123_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_personnephysique',
            name='age',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
