# Generated by Django 3.1.1 on 2023-01-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0004_auto_20230123_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_client',
            old_name='my_file',
            new_name='fichier',
        ),
    ]
