# Generated by Django 3.1.1 on 2023-01-23 12:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0005_auto_20230123_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_client',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/file'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='model_personnephysique',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
