# Generated by Django 3.1.1 on 2023-01-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0014_model_usser_allow'),
        ('GestionCouriers', '0006_auto_20230123_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_client',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.entreprise'),
        ),
    ]
