# Generated by Django 3.1.1 on 2023-01-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0007_model_client_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_client',
            name='code_ent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
