# Generated by Django 3.1.1 on 2023-01-26 05:43

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0008_model_client_code_ent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_client',
            name='fichier',
        ),
        migrations.AlterField(
            model_name='model_client',
            name='code_ent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Model_dossiers_pp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pp', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/file'), upload_to='')),
                ('personnep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_fichiers_pp', to='GestionCouriers.model_personnephysique')),
            ],
        ),
        migrations.CreateModel(
            name='Model_dossiers_pm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pm', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/file'), upload_to='')),
                ('personnem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_fichiers_pm', to='GestionCouriers.model_personnemorale')),
            ],
        ),
    ]
