# Generated by Django 3.1.1 on 2023-01-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0009_auto_20230126_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_personnephysique',
            name='codex',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
