# Generated by Django 3.1.1 on 2023-01-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0010_model_personnephysique_codex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_personnephysique',
            name='codex',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
