# Generated by Django 3.1.1 on 2023-01-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0011_auto_20230126_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_client',
            name='apropos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
