# Generated by Django 3.1.1 on 2023-01-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0013_auto_20230127_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_personnephysique',
            name='codex',
        ),
        migrations.AddField(
            model_name='model_client',
            name='codex',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
