# Generated by Django 3.1.1 on 2023-02-03 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0019_model_moi'),
        ('GestionCouriers', '0014_auto_20230128_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_courrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_arriver', models.DateField(blank=True, null=True)),
                ('decision', models.TextField(blank=True, null=True)),
                ('concerne', models.CharField(blank=True, max_length=150, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('anotation', models.TextField(blank=True, null=True)),
                ('client_intitule', models.CharField(blank=True, max_length=150, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionCouriers.model_client')),
            ],
        ),
        migrations.CreateModel(
            name='Model_TypeCourrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ent', models.CharField(blank=True, max_length=150, null=True)),
                ('typecourrir', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.entreprise')),
            ],
        ),
        migrations.DeleteModel(
            name='Model_dossiers_pm',
        ),
        migrations.AddField(
            model_name='model_courrier',
            name='typecourrir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionCouriers.model_typecourrier'),
        ),
    ]
