# Generated by Django 3.1.1 on 2023-02-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0015_auto_20230203_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_typecourrier',
            name='code_ent',
        ),
        migrations.RemoveField(
            model_name='model_typecourrier',
            name='entreprise',
        ),
    ]
