# Generated by Django 3.1.1 on 2023-02-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0016_auto_20230203_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_typecourrier',
            name='typecourrir',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
