# Generated by Django 3.1.1 on 2023-02-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0017_auto_20230203_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_courrier',
            name='Date_arriver',
            field=models.DateField(auto_now_add=True),
        ),
    ]
