# Generated by Django 3.1.1 on 2023-02-03 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0018_auto_20230203_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_NatureCourrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='model_courrier',
            name='nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionCouriers.model_naturecourrier'),
        ),
    ]
