# Generated by Django 3.1.1 on 2023-02-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0019_auto_20230203_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_courrier',
            name='client',
        ),
        migrations.AddField(
            model_name='model_courrier',
            name='client_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionCouriers.model_personnemorale'),
        ),
        migrations.AddField(
            model_name='model_courrier',
            name='client_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionCouriers.model_personnephysique'),
        ),
    ]
