# Generated by Django 3.1.1 on 2023-02-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0019_model_moi'),
        ('GestionCouriers', '0022_auto_20230203_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_courrier',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.model_utilisateur'),
        ),
    ]
