# Generated by Django 3.1.1 on 2023-02-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0019_model_moi'),
        ('GestionCouriers', '0023_model_courrier_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_courrier',
            name='code_ent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='model_courrier',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.entreprise'),
        ),
    ]
