# Generated by Django 3.1.1 on 2023-02-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0024_auto_20230203_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_courrier',
            name='codex',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
