# Generated by Django 3.1.1 on 2023-02-03 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0025_model_courrier_codex'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_courrier',
            name='client_intitule_exp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='model_courrier',
            name='client_m_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_m_exp', to='GestionCouriers.model_personnemorale'),
        ),
        migrations.AddField(
            model_name='model_courrier',
            name='client_p_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_p_exp', to='GestionCouriers.model_personnephysique'),
        ),
    ]
