# Generated by Django 3.1.1 on 2023-02-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0019_model_moi'),
        ('GestionCouriers', '0027_model_agentaffectercourrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_courrier',
            name='anotation',
        ),
        migrations.CreateModel(
            name='Model_Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ent', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('codex', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_annitations', to='datacenter.model_utilisateur')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_courriers', to='datacenter.entreprise')),
            ],
        ),
    ]
