# Generated by Django 3.1.1 on 2023-02-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0028_auto_20230206_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_courrier',
            name='anotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_annotation', to='GestionCouriers.model_annotation'),
        ),
    ]
