# Generated by Django 3.1.1 on 2023-02-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0029_model_courrier_anotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_courrier',
            name='anotation',
        ),
        migrations.AddField(
            model_name='model_annotation',
            name='courrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_annotation', to='GestionCouriers.model_courrier'),
        ),
    ]
