# Generated by Django 4.1.6 on 2023-02-06 14:42

import GestionCouriers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCouriers', '0030_auto_20230206_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_courrier',
            name='Date_traitement',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='model_dossiers_pp',
            name='fichier_pp',
            field=models.FileField(blank=True, null=True, storage=GestionCouriers.models.select_storage, upload_to=''),
        ),
    ]
