# Generated by Django 3.1.1 on 2023-01-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datacenter', '0014_model_usser_allow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Employer',
            fields=[
                ('model_utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datacenter.model_utilisateur')),
                ('date_engagement', models.DateField(blank=True, null=True)),
            ],
            bases=('datacenter.model_utilisateur',),
        ),
        migrations.CreateModel(
            name='Model_Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_entreprise', to='ResourceHumaines.model_employer')),
            ],
        ),
        migrations.CreateModel(
            name='Model_Employer_Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(blank=True, max_length=10, null=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_fonction', to='datacenter.entreprise')),
            ],
        ),
    ]
