# Generated by Django 3.1.1 on 2023-01-29 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0014_model_usser_allow'),
        ('ResourceHumaines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_employer',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_fonction', to='ResourceHumaines.model_employer_fonction'),
        ),
        migrations.AlterField(
            model_name='model_employer_fonction',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonction_entreprise', to='datacenter.entreprise'),
        ),
        migrations.CreateModel(
            name='Model_Postes_Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(blank=True, max_length=10, null=True)),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_poste', to='ResourceHumaines.model_employer_fonction')),
            ],
        ),
    ]
