# Generated by Django 3.1.1 on 2023-01-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceHumaines', '0002_auto_20230129_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_employer',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_poste', to='ResourceHumaines.model_postes_fonction'),
        ),
    ]
