# Generated by Django 3.1.1 on 2023-01-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceHumaines', '0003_model_employer_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_employer_fonction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
