# Generated by Django 3.1.1 on 2023-01-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceHumaines', '0004_model_employer_fonction_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_employer_fonction',
            name='codex',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='model_observation',
            name='codex',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='model_postes_fonction',
            name='codex',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
