# Generated by Django 3.1.1 on 2023-01-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0015_model_utilisateur_codex'),
        ('ResourceHumaines', '0005_auto_20230130_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_employer_fonction',
            name='code_ent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='model_observation',
            name='code_ent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='model_observation',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observqtion_entreprise', to='datacenter.entreprise'),
        ),
        migrations.AddField(
            model_name='model_postes_fonction',
            name='code_ent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='model_postes_fonction',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poste_entreprise', to='datacenter.entreprise'),
        ),
    ]
