# Generated by Django 3.1.1 on 2023-02-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0018_model_utilisateur_code_ent'),
        ('ResourceHumaines', '0007_auto_20230131_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_employer_fonction_poste',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_fonction_poste', to='datacenter.model_utilisateur'),
        ),
        migrations.AlterField(
            model_name='model_observation',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_entreprise', to='datacenter.model_utilisateur'),
        ),
    ]
